#!/usr/bin/env bash

OTAI_CONFIG_DIR="/etc/open-ticket-ai"
OTAI_CONFIG_FILE="${OTAI_CONFIG_DIR}/config.yml"
OTAI_SERVICE_NAME="open-ticket-ai"
OTAI_USER="otai"
OTAI_GROUP="otai"
OTAI_VENV_DIR="/opt/open-ticket-ai/venv"
OTAI_LOG_DIR="/var/log/open-ticket-ai"

# shellcheck source=lib/ai_eval.sh
source "$(dirname "${BASH_SOURCE[0]}")/ai_eval.sh"

setup_python_env() {
	info "Setting up Python environment..."
	if ! command -v python3 &>/dev/null; then
		pkg_install python3
	fi
	pkg_install python3-pip python3-venv
	if ! command -v uv &>/dev/null; then
		info "Installing uv (fast Python package manager)..."
		curl -LsSf https://astral.sh/uv/install.sh | sh || {
			warn "uv install via script failed, falling back to pip"
		}
		if [ -f "$HOME/.local/bin/uv" ]; then
			cp "$HOME/.local/bin/uv" /usr/local/bin/uv 2>/dev/null || true
			chmod 755 /usr/local/bin/uv 2>/dev/null || true
		fi
		export PATH="$HOME/.local/bin:/usr/local/bin:$PATH"
		if ! command -v uv &>/dev/null; then
			pip3 install uv || warn "uv pip install failed"
		fi
	fi
	register_result "Python Env" "OK" "Python 3 and uv ready"
}

create_otai_user() {
	info "Creating system user $OTAI_USER..."
	groupadd -r "$OTAI_GROUP" 2>/dev/null || true
	useradd -r -d /opt/open-ticket-ai -s /bin/bash -g "$OTAI_GROUP" "$OTAI_USER" 2>/dev/null || true
	register_result "OTAI User" "OK" "System user $OTAI_USER created"
}

create_otai_dirs() {
	info "Creating Open Ticket AI directories..."
	mkdir -p "$OTAI_CONFIG_DIR" "$OTAI_VENV_DIR" "$OTAI_LOG_DIR" /opt/open-ticket-ai/models /opt/open-ticket-ai/data
	chown -R "${OTAI_USER}:${OTAI_GROUP}" /opt/open-ticket-ai "$OTAI_LOG_DIR"
	chmod 755 /opt/open-ticket-ai
	register_result "OTAI Dirs" "OK" "Directories created"
}

install_otai_packages() {
	info "Installing Open Ticket AI Python packages..."
	local uv_path
	uv_path=$(command -v uv 2>/dev/null || echo "")
	if [ -n "$uv_path" ]; then
		sudo -u "$OTAI_USER" "$uv_path" venv "$OTAI_VENV_DIR" || die "Failed to create uv venv"
		sudo -u "$OTAI_USER" "${OTAI_VENV_DIR}/bin/pip" install open-ticket-ai otai-otobo-znuny otai-hf-local || {
			warn "pip install via uv venv failed, falling back to system pip3"
			pip3 install open-ticket-ai otai-otobo-znuny otai-hf-local
		}
	else
		pip3 install open-ticket-ai otai-otobo-znuny otai-hf-local || die "Failed to install OTAI packages"
	fi
	register_result "OTAI Packages" "OK" "open-ticket-ai, otai-otobo-znuny, otai-hf-local installed"
}

import_otai_webservice() {
	local otobo_root="$1"
	local otobo_user="$2"
	local ws_file="${otobo_root}/var/webservices/OpenTicketAI.yml"

	info "Importing Open Ticket AI GenericInterface web service..."

	if [ -f "$ws_file" ]; then
		cd "$otobo_root" || die "Cannot cd to $otobo_root"
		sudo -u "$otobo_user" perl bin/otobo.Console.pl Admin::WebService::Import "$ws_file" 2>/dev/null ||
			warn "Web service import failed (may already exist)"
		register_result "OTAI WebService" "OK" "GenericInterface web service imported"
	else
		warn "Web service template not found at $ws_file"
		info "Creating minimal web service config manually..."

		cat >/tmp/OpenTicketAI.yml <<YML
---
Debugger:
  DebugThreshold: error
  TestMode: '0'
Description: Open Ticket AI integration
RemoteSystem: ''
Provider:
  Transport:
    Type: HTTP::REST
    Config:
      AdditionalHeaders: ''
      Controller: Ticket
      Route: /otai
      Mapping: ''
      RouteQuery: ''
    MaxLength: '100000000'
    FailOver: ~
  Operation:
    TicketCreate:
      Type: Ticket::TicketCreate
    TicketGet:
      Type: Ticket::TicketGet
    TicketSearch:
      Type: Ticket::TicketSearch
    TicketUpdate:
      Type: Ticket::TicketUpdate
    ArticleCreate:
      Type: Article::ArticleCreate
    ArticleGet:
      Type: Article::ArticleGet
    QueueGet:
      Type: Queue::QueueGet
    SessionCreate:
      Type: Session::SessionCreate
  Requester:
    Transport:
      Type: HTTP::REST
    Invoker:
      GetNewTickets:
        Type: Ticket::TicketSearch
        Config:
          Mapping: ~
      UpdateTicket:
        Type: Ticket::TicketUpdate
        Config:
          Mapping: ~
YML
		sudo -u "$otobo_user" mkdir -p "${otobo_root}/var/webservices"
		cp /tmp/OpenTicketAI.yml "$ws_file"
		cd "$otobo_root" || die "Cannot cd to $otobo_root"
		sudo -u "$otobo_user" perl bin/otobo.Console.pl Admin::WebService::Import "$ws_file" 2>/dev/null ||
			warn "Web service import had issues"
		rm -f /tmp/OpenTicketAI.yml
		register_result "OTAI WebService" "OK" "Web service created manually"
	fi
}

generate_otai_config() {
	local fqdn="$1"
	local api_user="$2"
	local api_pass="$3"
	local queue="${4:-Raw}"
	local poll_interval="${5:-60}"
	local model="${6:-MiniLM}"

	info "Generating Open Ticket AI config at $OTAI_CONFIG_FILE..."

	cat >"$OTAI_CONFIG_FILE" <<YML
# Open Ticket AI Configuration
# Generated by OTOBOSuite

server:
  host: 0.0.0.0
  port: 8080
  log_level: info
  log_file: ${OTAI_LOG_DIR}/otai.log

otobo:
  url: "http://${fqdn}/otobo"
  api_user: "${api_user}"
  api_password: "${api_pass}"
  web_service: "OpenTicketAI"
  poll_interval: ${poll_interval}
  default_queue: "${queue}"

processing:
  pipeline:
    - classifier
    - priority
    - auto_reply
  classifier:
    model: "${model}"
    confidence_threshold: 0.7
  auto_reply:
    enabled: true
    template_dir: /opt/open-ticket-ai/data/templates
YML

	chown "${OTAI_USER}:${OTAI_GROUP}" "$OTAI_CONFIG_FILE"
	chmod 640 "$OTAI_CONFIG_FILE"
	register_result "OTAI Config" "OK" "Config written to $OTAI_CONFIG_FILE"
}

download_ai_model() {
	local model="$1"
	local model_dir="/opt/open-ticket-ai/models"

	if [ "$model" = "skip" ]; then
		info "Skipping model download (user choice)"
		register_result "AI Model" "INFO" "Model download skipped"
		return
	fi

	local model_name=""
	case "$model" in
	"bert") model_name="bert-base-uncased" ;;
	"roberta") model_name="roberta-base" ;;
	"distilbert") model_name="distilbert-base-uncased" ;;
	"minilm" | "MiniLM" | "minilm-l6-v2") model_name="sentence-transformers/all-MiniLM-L6-v2" ;;
	*) model_name="sentence-transformers/all-MiniLM-L6-v2" ;;
	esac

	info "Downloading model $model_name (this may take a while)..."
	mkdir -p "$model_dir"
	chown "${OTAI_USER}:${OTAI_GROUP}" "$model_dir"

	if command -v otai-download-model &>/dev/null; then
		sudo -u "$OTAI_USER" otai-download-model --model "$model_name" --output "$model_dir" ||
			warn "otai-download-model failed"
	else
		# Fallback: use huggingface_hub via Python
		pip3 install huggingface-hub 2>/dev/null || true
		sudo -u "$OTAI_USER" python3 -c "
from huggingface_hub import snapshot_download
snapshot_download(repo_id='$model_name', local_dir='$model_dir')
" 2>/dev/null || warn "Model download using huggingface_hub failed"
	fi

	register_result "AI Model" "OK" "Model $model_name downloaded to $model_dir"
}

create_otai_systemd_service() {
	info "Creating systemd service for Open Ticket AI..."

	cat >"/etc/systemd/system/${OTAI_SERVICE_NAME}.service" <<SYSTEMD
[Unit]
Description=Open Ticket AI - Intelligent ticket automation for OTOBO
After=network.target
Wants=network.target

[Service]
Type=simple
User=${OTAI_USER}
Group=${OTAI_GROUP}
WorkingDirectory=/opt/open-ticket-ai
Environment=PYTHONUNBUFFERED=1
Environment=OTAI_CONFIG=${OTAI_CONFIG_FILE}
ExecStart=${OTAI_VENV_DIR}/bin/otai-server --config ${OTAI_CONFIG_FILE}
Restart=on-failure
RestartSec=10
StandardOutput=append:${OTAI_LOG_DIR}/otai.log
StandardError=append:${OTAI_LOG_DIR}/otai_error.log

[Install]
WantedBy=multi-user.target
SYSTEMD

	systemctl daemon-reload
	register_result "OTAI Service" "OK" "systemd service created"
}

start_otai() {
	info "Starting Open Ticket AI service..."
	systemctl enable "$OTAI_SERVICE_NAME"
	systemctl start "$OTAI_SERVICE_NAME"

	if systemctl is-active "$OTAI_SERVICE_NAME" &>/dev/null; then
		register_result "OTAI Start" "OK" "Open Ticket AI is running"
	else
		warn "Open Ticket AI service failed to start, check journalctl -u $OTAI_SERVICE_NAME"
		register_result "OTAI Start" "WARN" "Service may not be running"
	fi
}

evaluate_current_model() {
	run_evaluation
}

switch_model() {
	echo ""
	echo "========================================"
	echo "  Switch AI Model"
	echo "========================================"
	echo "  1) MiniLM (all-MiniLM-L6-v2) - ~80MB"
	echo "  2) DistilBERT (distilbert-base-uncased) - ~260MB"
	echo "  3) BERT (bert-base-uncased) - ~440MB"
	echo "  4) RoBERTa (roberta-base) - ~500MB"
	echo "  5) Fine-tuned model (if available)"
	echo "========================================"

	local choice
	read -r -p "Select model [1]: " choice
	local model_name=""
	case "${choice:-1}" in
	1) model_name="sentence-transformers/all-MiniLM-L6-v2" ;;
	2) model_name="distilbert-base-uncased" ;;
	3) model_name="bert-base-uncased" ;;
	4) model_name="roberta-base" ;;
	5)
		if [ -f "${OTAI_FINE_TUNED_DIR}/config.json" ]; then
			model_name="$OTAI_FINE_TUNED_DIR"
		else
			warn "No fine-tuned model found at $OTAI_FINE_TUNED_DIR"
			return
		fi
		;;
	*) model_name="sentence-transformers/all-MiniLM-L6-v2" ;;
	esac

	local model_path="${model_name}"
	if echo "$model_name" | grep -q '/'; then
		# HuggingFace model ID — check local cache under models dir
		local cache_name
		cache_name=$(basename "$model_name")
		if [ -d "/opt/open-ticket-ai/models/${cache_name}" ]; then
			model_path="/opt/open-ticket-ai/models/${cache_name}"
		else
			download_ai_model "$model_name"
		fi
	elif [ ! -d "$model_name" ]; then
		download_ai_model "$model_name"
	fi

	sed -i "s|model:.*|model: \"${model_name}\"|" "$OTAI_CONFIG_FILE"
	systemctl restart open-ticket-ai.service
	info "Switched to model: $model_name"
	register_result "ModelSwitch" "OK" "Switched to $model_name"
}

undo_ai() {
	info "Rolling back Open Ticket AI..."
	systemctl stop "$OTAI_SERVICE_NAME" 2>/dev/null || true
	systemctl disable "$OTAI_SERVICE_NAME" 2>/dev/null || true
	rm -f "/etc/systemd/system/${OTAI_SERVICE_NAME}.service"
	rm -rf /opt/open-ticket-ai "$OTAI_CONFIG_DIR" "$OTAI_LOG_DIR"
	userdel -r "$OTAI_USER" 2>/dev/null || true
	groupdel "$OTAI_GROUP" 2>/dev/null || true
	systemctl daemon-reload
	register_result "UndoAI" "OK" "Open Ticket AI removed"
}

install_ai_module() {
	local otobo_root="${1:-/opt/otobo}"
	local otobo_user="${2:-otobo}"
	local fqdn="$3"
	local api_pass="$4"
	local model="${5:-minilm}"
	local queue="${6:-Raw}"
	local poll_interval="${7:-60}"
	local api_user="open_ticket_ai"

	# Resolve short model name to HuggingFace ID
	local model_full=""
	case "$model" in
	"bert") model_full="bert-base-uncased" ;;
	"roberta") model_full="roberta-base" ;;
	"distilbert") model_full="distilbert-base-uncased" ;;
	"mini LM" | "minilm" | "minilm-l6-v2") model_full="sentence-transformers/all-MiniLM-L6-v2" ;;
	*) model_full="sentence-transformers/all-MiniLM-L6-v2" ;;
	esac
	local api_email="otai@${fqdn}"

	echo ""
	echo "========================================"
	echo "  Installing Open Ticket AI Module"
	echo "========================================"

	setup_python_env
	create_otai_user
	create_otai_dirs

	# Configure OTOBO API user
	configure_otobo_api_user "$otobo_root" "$otobo_user" "$api_user" "$api_pass" "$api_email"

	# Import web service
	import_otai_webservice "$otobo_root" "$otobo_user"

	# Install Python packages
	install_otai_packages

	# Generate config (use resolved full model name)
	generate_otai_config "$fqdn" "$api_user" "$api_pass" "$queue" "$poll_interval" "$model_full"

	# Download model
	download_ai_model "$model_full"

	# Create and start service
	create_otai_systemd_service
	start_otai

	echo ""
	echo "========================================"
	echo "  Open Ticket AI Installation Complete"
	echo "========================================"
	echo "  Config:   $OTAI_CONFIG_FILE"
	echo "  API User: $api_user"
	echo "  API Pass: $api_pass"
	echo "  Service:  $OTAI_SERVICE_NAME"
	echo "========================================"
}
