#!/usr/bin/env bash

CONFIG_FILE="/etc/otobo-installer.conf"

load_config() {
	local config_path="${1:-$CONFIG_FILE}"
	if [[ -f "$config_path" ]]; then
		# shellcheck disable=SC1090
		source "$config_path"
		return 0
	fi
	return 1
}

config_value() {
	local key="$1"
	local default="$2"
	local val

	val=$(eval "echo \${${key}:-}" 2>/dev/null)
	if [[ -n "$val" ]]; then
		echo "$val"
	else
		echo "$default"
	fi
}

config_is_complete() {
	local required_keys=("$@")
	local key
	for key in "${required_keys[@]}"; do
		local val
		val=$(config_value "$key" "")
		if [[ -z "$val" ]]; then
			return 1
		fi
	done
	return 0
}

save_config() {
	local tmp
	tmp=$(mktemp)
	cat >"$tmp" <<EOF
# OTOBO Installer Configuration
# Generated by OTOBOSuite

OTOBO_ROOT="${OTOBO_ROOT:-/opt/otobo}"
OTOBO_USER="${OTOBO_USER:-otobo}"
OTOBO_GROUP="${OTOBO_GROUP:-www-data}"
DB_ENGINE="${DB_ENGINE:-mariadb}"
DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-3306}"
DB_NAME="${DB_NAME:-otobo}"
DB_USER="${DB_USER:-otobo}"
DB_PASS="${DB_PASS:-}"
WEB_SERVER="${WEB_SERVER:-apache}"
FQDN="${FQDN:-$(hostname -f)}"
SSL_MODE="${SSL_MODE:-none}"
SSL_EMAIL="${SSL_EMAIL:-}"
INSTALL_AI="${INSTALL_AI:-no}"
AI_MODEL="${AI_MODEL:-minilm}"
AI_QUEUE="${AI_QUEUE:-Raw}"
AI_POLL_INTERVAL="${AI_POLL_INTERVAL:-60}"
INSTALL_HARDENING="${INSTALL_HARDENING:-no}"
INSTALL_MONITORING="${INSTALL_MONITORING:-no}"
EOF
	if [ -d /etc ]; then
		cp "$tmp" "$CONFIG_FILE"
		chmod 644 "$CONFIG_FILE"
		info "Config saved to $CONFIG_FILE"
	fi
	rm -f "$tmp"
}
