---
all:
  children:
    ubuntu:
      hosts:
        ubuntu2404:
          ansible_host: 192.168.56.10
          ansible_user: vagrant
    debian:
      hosts:
        debian12:
          ansible_host: 192.168.56.11
          ansible_user: vagrant
